-- 1.
CREATE TABLE EMPIDX AS SELECT * FROM EMP;

CREATE INDEX IDX_EMPIDX_EMPNO ON EMPIDX(EMPNO);

SELECT * FROM USER_INDEXES;

-- 2.
CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM, 'O', 'X') AS COMM FROM EMPIDX WHERE SAL > 1500)
WITH READ ONLY;

-- 3.
CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT;

CREATE SEQUENCE SEQ_DEPTSEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE; 

INSERT INTO DEPTSEQ 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');

INSERT INTO DEPTSEQ 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');

INSERT INTO DEPTSEQ
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');
