-- 1.
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, DEPTNO, D.DNAME
FROM EMP E NATURAL JOIN DEPT D
WHERE (E.JOB, D.DNAME) IN (SELECT E.JOB, D.DNAME FROM EMP E, DEPT D WHERE ENAME = 'ALLEN')
ORDER BY E.SAL DESC;

-- 2.
-- 표준 방식
SELECT E.EMPNO, E.ENAME, D.DNAME, TO_CHAR(E.HIREDATE, 'YYYY-MM-DD') AS HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO) JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)							
WHERE SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO ASC;
-- 비표준 방식
SELECT E.EMPNO, E.ENAME, D.DNAME, TO_CHAR(E.HIREDATE, 'YYYY-MM-DD') AS HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S 
WHERE E.DEPTNO = D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO ASC;

-- 3.
SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.DEPTNO = 10
AND JOB NOT IN (SELECT JOB FROM EMP E WHERE E.DEPTNO = 30);

-- 4.
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > (SELECT MAX(SAL) FROM EMP E WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S ON(E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > ALL (SELECT SAL FROM EMP E WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;
